-- Add new FAQ columns
ALTER TABLE salons ADD COLUMN IF NOT EXISTS review_summary TEXT;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS about TEXT;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS customers_saying TEXT;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS health_wellbeing_care TEXT;

-- Add/rename service columns that may be missing or have wrong names
ALTER TABLE salons ADD COLUMN IF NOT EXISTS gel_extensions BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS sns_dip_powder BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS builders_gel_biab BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS lash_extensions BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS lash_lift_tint BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS brows BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS injectables BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS tanning BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS cosmetic_tattoo BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS haircuts BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS spa_hand_foot_treatment BOOLEAN DEFAULT FALSE;

-- Add language columns
ALTER TABLE salons ADD COLUMN IF NOT EXISTS english BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS spanish BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS vietnamese BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS chinese BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS korean BOOLEAN DEFAULT FALSE;

-- Add specialty columns (renamed from old ones)
ALTER TABLE salons ADD COLUMN IF NOT EXISTS qualified_technicians BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS experienced_team BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS award_winning_staff BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS master_nail_artist BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS bridal_nails BOOLEAN DEFAULT FALSE;

-- Add appointment type columns
ALTER TABLE salons ADD COLUMN IF NOT EXISTS appointment_required BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS walk_ins_welcome BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS group_bookings BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS mobile_nails BOOLEAN DEFAULT FALSE;

-- Add amenity/space columns (some renamed)
ALTER TABLE salons ADD COLUMN IF NOT EXISTS child_friendly BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS adult_only BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS pet_friendly BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS lgbtqi_friendly BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS autoclave_sterilisation BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS led_curing BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS clean_ethical_products BOOLEAN DEFAULT FALSE;
ALTER TABLE salons ADD COLUMN IF NOT EXISTS vegan_polish BOOLEAN DEFAULT FALSE;

-- Comment: Some columns may already exist with old names, those will be handled in the import script
