import { NextRequest, NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams
    const limit = parseInt(searchParams.get('limit') || '8')

    // Fetch featured salons (top rated salons since is_featured isn't set yet)
    const { data: salons, error } = await supabase
      .from('salons')
      .select(`
        id,
        name,
        slug,
        city,
        address,
        phone,
        website,
        description,
        rating,
        is_verified,
        is_featured,
        parking,
        accepts_walk_ins,
        latitude,
        longitude,
        manicure,
        pedicure,
        gel_nails,
        acrylic_nails,
        nail_art,
        master_artist,
        certified_technicians,
        experienced_staff,
        cover_image_url,
        gallery_images,
        state,
        country,
        postal_code
      `)
      .eq('is_published', true)
      .order('rating', { ascending: false })
      .order('name', { ascending: true })
      .limit(limit)

    if (error) {
      console.error('Supabase error:', error)
      // Return mock data instead of error when database is not configured
      return NextResponse.json({
        salons: getMockFeaturedSalons(limit),
        count: limit,
        success: true,
        mock: true
      })
    }

    // If no salons found, return mock data
    if (!salons || salons.length === 0) {
      console.log('No salons found in database, returning mock data')
      return NextResponse.json({
        salons: getMockFeaturedSalons(limit),
        count: limit,
        success: true,
        mock: true
      })
    }

    // Transform salons
    const transformedSalons = (salons || []).map(salon => ({
      ...salon,
      services_offered: [
        salon.manicure && 'Manicure',
        salon.pedicure && 'Pedicure',
        salon.gel_nails && 'Gel Nails',
        salon.acrylic_nails && 'Acrylic Nails',
        salon.nail_art && 'Nail Art'
      ].filter(Boolean),
      specialties: [
        salon.master_artist && 'Master Nail Artist',
        salon.certified_technicians && 'Certified Technicians',
        salon.experienced_staff && 'Experienced Team'
      ].filter(Boolean),
      currency: 'AUD',
      country: 'Australia',
      state: 'VIC', // Will be updated from cities table
      languages_spoken: ['English'],
      price_range: 'mid-range',
      price_from: 35,
      average_rating: salon.rating,
      review_count: 0
    }))

    return NextResponse.json({
      salons: transformedSalons,
      count: transformedSalons.length,
      success: true
    })
  } catch (error) {
    console.error('API error:', error)
    // Return mock data instead of error
    const limit = parseInt(request.nextUrl.searchParams.get('limit') || '8')
    return NextResponse.json({
      salons: getMockFeaturedSalons(limit),
      count: limit,
      success: true,
      mock: true
    })
  }
}

// Mock data for when database is not configured
function getMockFeaturedSalons(limit: number) {
  const mockSalons = [
    {
      id: '1',
      name: 'Luxe Nails & Spa',
      slug: 'luxe-nails-spa-melbourne',
      city: 'Melbourne',
      address: '123 Collins Street',
      state: 'VIC',
      country: 'Australia',
      postal_code: '3000',
      phone: '(03) 9xxx xxxx',
      website: 'https://example.com',
      description: 'Premium nail salon in the heart of Melbourne CBD',
      rating: 4.9,
      is_verified: true,
      is_featured: true,
      parking: true,
      accepts_walk_ins: true,
      latitude: -37.8136,
      longitude: 144.9631,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: true,
      nail_art: true,
      master_artist: true,
      certified_technicians: true,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Acrylic Nails', 'Nail Art'],
      specialties: ['Master Nail Artist', 'Certified Technicians', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'premium',
      price_from: 45,
      average_rating: 4.9,
      review_count: 127
    },
    {
      id: '2',
      name: 'Bella Nails Studio',
      slug: 'bella-nails-studio-sydney',
      city: 'Sydney',
      address: '456 George Street',
      state: 'NSW',
      country: 'Australia',
      postal_code: '2000',
      phone: '(02) 9xxx xxxx',
      website: 'https://example.com',
      description: 'Modern nail studio with expert technicians',
      rating: 4.8,
      is_verified: true,
      is_featured: true,
      parking: false,
      accepts_walk_ins: true,
      latitude: -33.8688,
      longitude: 151.2093,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: true,
      nail_art: true,
      master_artist: false,
      certified_technicians: true,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1610992015732-2449b76344bc?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Acrylic Nails', 'Nail Art'],
      specialties: ['Certified Technicians', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'mid-range',
      price_from: 35,
      average_rating: 4.8,
      review_count: 89
    },
    {
      id: '3',
      name: 'Glamour Nails',
      slug: 'glamour-nails-brisbane',
      city: 'Brisbane',
      address: '789 Queen Street',
      state: 'QLD',
      country: 'Australia',
      postal_code: '4000',
      phone: '(07) 3xxx xxxx',
      website: 'https://example.com',
      description: 'Trendy nail salon with the latest designs',
      rating: 4.7,
      is_verified: true,
      is_featured: true,
      parking: true,
      accepts_walk_ins: false,
      latitude: -27.4698,
      longitude: 153.0251,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: false,
      nail_art: true,
      master_artist: true,
      certified_technicians: true,
      experienced_staff: false,
      cover_image_url: 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Nail Art'],
      specialties: ['Master Nail Artist', 'Certified Technicians'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'mid-range',
      price_from: 40,
      average_rating: 4.7,
      review_count: 65
    },
    {
      id: '4',
      name: 'Perfect Polish',
      slug: 'perfect-polish-perth',
      city: 'Perth',
      address: '321 Murray Street',
      state: 'WA',
      country: 'Australia',
      postal_code: '6000',
      phone: '(08) 9xxx xxxx',
      website: 'https://example.com',
      description: 'Experienced nail technicians delivering perfection',
      rating: 4.9,
      is_verified: true,
      is_featured: true,
      parking: true,
      accepts_walk_ins: true,
      latitude: -31.9505,
      longitude: 115.8605,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: true,
      nail_art: true,
      master_artist: true,
      certified_technicians: true,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1599948128020-9a44b0bc8f8a?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Acrylic Nails', 'Nail Art'],
      specialties: ['Master Nail Artist', 'Certified Technicians', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'premium',
      price_from: 50,
      average_rating: 4.9,
      review_count: 143
    },
    {
      id: '5',
      name: 'Serenity Nails',
      slug: 'serenity-nails-adelaide',
      city: 'Adelaide',
      address: '654 Rundle Mall',
      state: 'SA',
      country: 'Australia',
      postal_code: '5000',
      phone: '(08) 8xxx xxxx',
      website: 'https://example.com',
      description: 'Relaxing atmosphere with professional nail care',
      rating: 4.6,
      is_verified: true,
      is_featured: true,
      parking: false,
      accepts_walk_ins: true,
      latitude: -34.9285,
      longitude: 138.6007,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: true,
      nail_art: false,
      master_artist: false,
      certified_technicians: true,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1587402092301-725e37c70fd8?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Acrylic Nails'],
      specialties: ['Certified Technicians', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'mid-range',
      price_from: 32,
      average_rating: 4.6,
      review_count: 54
    },
    {
      id: '6',
      name: 'Elite Nails',
      slug: 'elite-nails-canberra',
      city: 'Canberra',
      address: '987 City Walk',
      state: 'ACT',
      country: 'Australia',
      postal_code: '2600',
      phone: '(02) 6xxx xxxx',
      website: 'https://example.com',
      description: 'Premium nail services in the capital',
      rating: 4.8,
      is_verified: true,
      is_featured: true,
      parking: true,
      accepts_walk_ins: false,
      latitude: -35.2809,
      longitude: 149.1300,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: true,
      nail_art: true,
      master_artist: true,
      certified_technicians: true,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1562346529-de6e056586fc?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Acrylic Nails', 'Nail Art'],
      specialties: ['Master Nail Artist', 'Certified Technicians', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'premium',
      price_from: 48,
      average_rating: 4.8,
      review_count: 98
    },
    {
      id: '7',
      name: 'Nail Artistry',
      slug: 'nail-artistry-hobart',
      city: 'Hobart',
      address: '159 Elizabeth Street',
      state: 'TAS',
      country: 'Australia',
      postal_code: '7000',
      phone: '(03) 6xxx xxxx',
      website: 'https://example.com',
      description: 'Creative nail art and classic styles',
      rating: 4.7,
      is_verified: true,
      is_featured: true,
      parking: false,
      accepts_walk_ins: true,
      latitude: -42.8821,
      longitude: 147.3272,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: false,
      nail_art: true,
      master_artist: true,
      certified_technicians: false,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1604902396830-aca29e19b067?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Nail Art'],
      specialties: ['Master Nail Artist', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'mid-range',
      price_from: 38,
      average_rating: 4.7,
      review_count: 41
    },
    {
      id: '8',
      name: 'Divine Nails',
      slug: 'divine-nails-darwin',
      city: 'Darwin',
      address: '753 Smith Street',
      state: 'NT',
      country: 'Australia',
      postal_code: '0800',
      phone: '(08) 8xxx xxxx',
      website: 'https://example.com',
      description: 'Top-rated nail salon in Darwin',
      rating: 4.5,
      is_verified: true,
      is_featured: true,
      parking: true,
      accepts_walk_ins: true,
      latitude: -12.4634,
      longitude: 130.8456,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: true,
      nail_art: false,
      master_artist: false,
      certified_technicians: true,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1606206873293-d94bbbc05904?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Acrylic Nails'],
      specialties: ['Certified Technicians', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'budget',
      price_from: 28,
      average_rating: 4.5,
      review_count: 33
    },
    {
      id: '9',
      name: 'Chic Nails',
      slug: 'chic-nails-gold-coast',
      city: 'Gold Coast',
      address: '234 Surfers Paradise Boulevard',
      state: 'QLD',
      country: 'Australia',
      postal_code: '4217',
      phone: '(07) 5xxx xxxx',
      website: 'https://example.com',
      description: 'Beachside nail salon with tropical vibes',
      rating: 4.8,
      is_verified: true,
      is_featured: true,
      parking: true,
      accepts_walk_ins: true,
      latitude: -28.0023,
      longitude: 153.4145,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: true,
      nail_art: true,
      master_artist: true,
      certified_technicians: true,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1610992015732-2449b76344bc?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Acrylic Nails', 'Nail Art'],
      specialties: ['Master Nail Artist', 'Certified Technicians', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'mid-range',
      price_from: 42,
      average_rating: 4.8,
      review_count: 156
    },
    {
      id: '10',
      name: 'Radiance Nails',
      slug: 'radiance-nails-newcastle',
      city: 'Newcastle',
      address: '567 Hunter Street',
      state: 'NSW',
      country: 'Australia',
      postal_code: '2300',
      phone: '(02) 4xxx xxxx',
      website: 'https://example.com',
      description: 'Award-winning nail salon with exceptional service',
      rating: 4.9,
      is_verified: true,
      is_featured: true,
      parking: false,
      accepts_walk_ins: false,
      latitude: -32.9283,
      longitude: 151.7817,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: true,
      nail_art: true,
      master_artist: true,
      certified_technicians: true,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1599948128020-9a44b0bc8f8a?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Acrylic Nails', 'Nail Art'],
      specialties: ['Master Nail Artist', 'Certified Technicians', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'premium',
      price_from: 55,
      average_rating: 4.9,
      review_count: 201
    },
    {
      id: '11',
      name: 'Bliss Nails & Beauty',
      slug: 'bliss-nails-wollongong',
      city: 'Wollongong',
      address: '891 Crown Street',
      state: 'NSW',
      country: 'Australia',
      postal_code: '2500',
      phone: '(02) 4xxx xxxx',
      website: 'https://example.com',
      description: 'Full-service nail and beauty salon',
      rating: 4.6,
      is_verified: true,
      is_featured: true,
      parking: true,
      accepts_walk_ins: true,
      latitude: -34.4278,
      longitude: 150.8931,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: true,
      nail_art: false,
      master_artist: false,
      certified_technicians: true,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1562346529-de6e056586fc?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Acrylic Nails'],
      specialties: ['Certified Technicians', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'mid-range',
      price_from: 36,
      average_rating: 4.6,
      review_count: 72
    },
    {
      id: '12',
      name: 'Prestige Nails',
      slug: 'prestige-nails-sunshine-coast',
      city: 'Sunshine Coast',
      address: '445 Horton Parade',
      state: 'QLD',
      country: 'Australia',
      postal_code: '4558',
      phone: '(07) 5xxx xxxx',
      website: 'https://example.com',
      description: 'Luxury nail experience on the Sunshine Coast',
      rating: 4.9,
      is_verified: true,
      is_featured: true,
      parking: true,
      accepts_walk_ins: false,
      latitude: -26.6500,
      longitude: 153.0667,
      manicure: true,
      pedicure: true,
      gel_nails: true,
      acrylic_nails: true,
      nail_art: true,
      master_artist: true,
      certified_technicians: true,
      experienced_staff: true,
      cover_image_url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800',
      gallery_images: [],
      services_offered: ['Manicure', 'Pedicure', 'Gel Nails', 'Acrylic Nails', 'Nail Art'],
      specialties: ['Master Nail Artist', 'Certified Technicians', 'Experienced Team'],
      currency: 'AUD',
      languages_spoken: ['English'],
      price_range: 'premium',
      price_from: 52,
      average_rating: 4.9,
      review_count: 184
    }
  ]

  return mockSalons.slice(0, limit)
}
